spring:
  application:
    name: children-service-prod

  datasource:
    url: jdbc:mysql://localhost:3306/students_db_prod?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8086
